name: my first workflow

on: push

jobs: 
    first_job:
        runs-on: ubuntu-slim
        steps: 
        - name: checkout
          uses: actions/checkout@v6    
          
        - name: Welcome message
          run: echo "my first github action"

        - name: list files
          run: ls
              
        - name: read files
          run: cat README.md
