name: Generate ASCII workflow

on: push

jobs: 
    ascii_job:
        runs-on: ubuntu-22.04
        steps: 
        - name: checkout
          uses: actions/checkout@v6    

        - name: Execute shell script
          run: |
            chmod +x ascii.sh
            ./ascii.sh